### ISSUE TITLE
Error: Excpected expression in list of expressions

### ISSUE THREAD

**Issue by werneroi** [laurentVeliscek/swift-clocks#1]
I just brought the file over the my swift project but i get the above message in line 89:
displayLink = CADisplayLink(target: self, selector: #selector(update))

**Comment by laurentVeliscek** [comment]
Please could you post your code ? (you can attach files)

You're issue is not very clear...
What is the error message ?

**Comment by werneroi** [comment]
Hi man!
here are screen shots of the errors.
I simply downloaded your files, and then imported them into my project.
maybe i should do something else?

**Comment by laurentVeliscek** [comment]
I cannot see any image in your post...

:-/

**Comment by laurentVeliscek** [comment]
I plan to code a dummy MidiListener tomorrow.
I'll post the code here if it works.

What OS is your target ? ios, Mac os X ?

**Comment by werneroi** [comment]
here is a shareable link:
https://drive.google.com/open?id=0B7vqGFtIbPvQbm5Sa0hBRlJMVkU

i am on Xcode 7,2,1 building for IOS

**Comment by laurentVeliscek** [comment]
Very strange.

I checked my files and everything works fine here, in a playground or as an app in iPhone sim.

I’m on xCode 7.3.

What version if ios do you target ?

My email is laurent.veliscek at gmail.com. You can zip and post the whole project if you want.

But I think the midiListener solution is a better option.

I’ll let you know if I can experiment with success and I can share a minimal project.

Good night :-)

Laurent Veliscek.




> Le 16 mai 2016 à 21:19, werneroi <notifications@github.com> a écrit :
> 
> here is a shareable link:
> https://drive.google.com/open?id=0B7vqGFtIbPvQbm5Sa0hBRlJMVkU <https://drive.google.com/open?id=0B7vqGFtIbPvQbm5Sa0hBRlJMVkU>
> i am on Xcode 7,2,1 building for IOS
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub <https://github.com/laurentVeliscek/swift-clocks/issues/1#issuecomment-219519759>




Mes compos en téléchargement libre sont sur Soundcloud (musicatalogue) :

https://soundcloud.com/musicatalogue
